CREATE SCHEMA IF NOT EXISTS `Hillel2020` DEFAULT CHARACTER SET utf8 ;
USE `Hillel2020` ;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`isGroup` (
`Group_ID` INT NOT NULL AUTO_INCREMENT,
`Group_Name` VARCHAR(45) NOT NULL,
PRIMARY KEY (`Group_ID`))
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`Students` (
`Student_ID` INT NOT NULL AUTO_INCREMENT,
`Full_Name` VARCHAR(45) NOT NULL,
`HowToJoin` DATE NOT NULL,
`Group_ID` INT NOT NULL,
PRIMARY KEY (`Student_ID`),
INDEX `id_idx` (`Group_ID` ASC) VISIBLE,
FOREIGN KEY (`Group_ID`)
REFERENCES `Hillel2020`.`isGroup` (`Group_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`Departmen` (
`Departmen_ID` INT NOT NULL AUTO_INCREMENT,
`Name_Departmen` VARCHAR(45) NOT NULL,
`Big_Boss` VARCHAR(45) NOT NULL,
PRIMARY KEY (`Departmen_ID`))
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`Teachers` (
`Teachers_ID` INT NOT NULL AUTO_INCREMENT,
`Teacher_Name` VARCHAR(45) NOT NULL,
`Department` INT NOT NULL,
PRIMARY KEY (`Teachers_ID`),
INDEX `Департмент_idx` (`Department` ASC) VISIBLE,
FOREIGN KEY (`Department`)
REFERENCES `Hillel2020`.`Departmen` (`Departmen_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`Lessons` (
`Lesson_ID` INT NOT NULL AUTO_INCREMENT,
`Lesson_Name` VARCHAR(45) NOT NULL,
`Teacher` INT NOT NULL,
`Semestr` INT NOT NULL,
`Year` DATE NOT NULL,
PRIMARY KEY (`Lesson_ID`),
INDEX `Учитель_idx` (`Teacher` ASC) VISIBLE,
FOREIGN KEY (`Teacher`)
REFERENCES `Hillel2020`.`Teachers` (`Teachers_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Hillel2020`.`Grade` (
`Grade_ID` INT NOT NULL AUTO_INCREMENT,
`Student_ID` INT NOT NULL,
`Grade` INT NULL,
`Lesson_ID` INT NOT NULL,
PRIMARY KEY (`Grade_ID`),
INDEX `Урок_idx` (`Lesson_ID` ASC) VISIBLE,
INDEX `Студент_idx` (`Student_ID` ASC) VISIBLE,
FOREIGN KEY (`Student_ID`)
REFERENCES `Hillel2020`.`Students` (`Student_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `Урок`
FOREIGN KEY (`Lesson_ID`)
REFERENCES `Hillel2020`.`Lessons` (`Lesson_ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
    ENGINE = InnoDB;